version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend:/app/frontend
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    privileged: true
    user: root
    depends_on:
      - emulation-docker

  emulation-docker:
    build: ./emulation-docker
    image: rpi-emulator