version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vc-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.emulator
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - vc-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  vc-network:
    driver: bridge

volumes:
  redis_data: